# Dumps an nvasm .vso into a C header as a raw D3D shader token stream.
# Assemble with -d, otherwise the debug comment tokens are carried along as dead weight.
#
#   powershell -File tools\vso2header.ps1 -Source <input.vso> -Destination <output.h> -Name <array>

param(
    [Parameter(Mandatory=$true)][string]$Source,
    [Parameter(Mandatory=$true)][string]$Destination,
    [Parameter(Mandatory=$true)][string]$Name
)

$bytes = [IO.File]::ReadAllBytes($Source)
if ($bytes.Length % 4 -ne 0) { throw "$Source is not a whole number of dwords" }

$tokens = @(for ($i = 0; $i -lt $bytes.Length; $i += 4) { [BitConverter]::ToUInt32($bytes, $i) })

# Enough to catch pointing this at the wrong file, or at a truncated one.
if (($tokens[0] -shr 16) -ne 0xFFFE) {
    throw ("{0} does not start with a vertex shader version token (got 0x{1:X8})" -f $Source, $tokens[0])
}
if ($tokens[-1] -ne 0x0000FFFF) { throw "$Source does not end with D3DSIO_END" }

$lines = "// Generated by tools\vso2header.ps1 from $([IO.Path]::GetFileNameWithoutExtension($Source)).vs, do not edit.",
         "#pragma once",
         "",
         "static const unsigned long $Name[] = {"

for ($i = 0; $i -lt $tokens.Count; $i += 6) {
    $chunk = $tokens[$i..([Math]::Min($i + 5, $tokens.Count - 1))]
    $lines += "    " + (($chunk | ForEach-Object { "0x{0:X8}," -f $_ }) -join " ")
}
$lines += "};"

[IO.File]::WriteAllLines($Destination, $lines)
Write-Output ("{0}: {1} tokens ({2} bytes)" -f (Split-Path -Leaf $Source), $tokens.Count, $bytes.Length)
